Merge pull request #1 from WalkingPal/dev
WalkingPal/walking-pal-web pull request #14
Opened 2022-09-12 07:11 UTC by Pratham-Mishra178

2022-09-19 18:08 UTC, ashuvssut commented
![image](https://user-images.githubusercontent.com/60546840/191084716-e30c18b9-6ab6-43f5-b72f-59ed4e72e706.png)

2022-09-21 14:46 UTC, ashuvssut requested changes

2022-09-21 14:46 UTC, ashuvssut commented on pages/404/404.tsx
>  						mx={1}
remove all these system props.

use h1 variant of Typography instead

2022-10-02 04:56 UTC, Pratham-Mishra178 commented
> @Pratham-Mishra178 ![image](https://user-images.githubusercontent.com/60546840/191084716-e30c18b9-6ab6-43f5-b72f-59ed4e72e706.png)

i have used system props to give padding betwwen two texts

2022-10-02 07:26 UTC, ashuvssut commented
Please always check what changes I make to your PR.

As a maintianer I can commit changes to your forked remote repo. you should always pull my changes from your forked remote repo to check what changes I have made locally on your machine.

For, now I have removed stylings from your page. there was a lot of bad styles that made your page unresponsive.
mainly, you used media-queries. do not use media-queries. only use wherever its an absolute necessity.

I hope you have checked my changes that I made to your Previously merged PR

2022-10-02 07:30 UTC, merged

2022-10-02 08:17 UTC, Pratham-Mishra178 commented
> Please always check what changes I make to your PR.
> 
> As a maintianer I can commit changes to your forked remote repo. you should always pull my changes from your forked remote repo to check what changes I have made locally on your machine.
> 
> For, now I have removed stylings from your page. there was a lot of bad styles that made your page unresponsive. mainly, you used media-queries. do not use media-queries. only use wherever its an absolute necessity.
> 
> I hope you have checked my changes that I made to your Previously merged PRs. Learn from those changes. else ask me why I made those changes

yes I have understand this . Thank You!