bug: Need accessibility improvements
WalkingPal/walking-pal-web pull request #158
Opened 2022-10-26 15:48 UTC by senali-d

Accessibility improvements - FAQ

Issue: bug: need accessibility improvements #123

2022-10-26 15:53 UTC, ashuvssut requested changes

2022-10-26 15:53 UTC, ashuvssut commented on pages/faq/components/FAQsection.tsx
> +						<ul className={styles.list}>
No need to create extra `ul` elemenet.

You can create the `ul` element by editing Line 51
`<List component="div" disablePadding>` ---> `<List component="ul" disablePadding>` (or maybe simply `<List  disablePadding>`)

2022-10-26 16:10 UTC, ashuvssut commented
You still havent all the fixed the accessibility issues (errors)
![image](https://user-images.githubusercontent.com/60546840/198078264-796320e0-fd0a-426e-8af9-3c051a89d304.png)

Please read the issue's description carefully. You will know what need to be done

Refer this comment on PR https://github.com/WalkingPal/walking-pal-web/pull/127#issuecomment-1273714876

2022-10-26 18:50 UTC, senali-d commented
@ashuvssut 
- I skipped low contrast issue because you mention in the comment https://github.com/WalkingPal/walking-pal-web/pull/127#issuecomment-1273716663

- Missing form label issue is out of control. Because it is came with MUI.
  Multiline `TextField` generate two `textarea` element but only one element they assign `id`. There is no `id` for the hidden `textarea` element.

![textarea](https://user-images.githubusercontent.com/52546856/198110752-972b4331-5bfe-41fa-aff3-7c7d0f854c06.png)

2022-10-26 21:48 UTC, merged

2022-10-26 22:27 UTC, ashuvssut commented
If have fixed some of those webaim Alerts (warnings) (ref 965c7e6).

2022-10-26 22:27 UTC, ashuvssut commented
@senali-d there are two more pages that need accessibility improvements: Register & 404 page. Your can take those up if you want to work on them.

2022-10-27 17:37 UTC, senali-d commented
> @senali-d there are two more pages that need accessibility improvements: Register & 404 page. Your can take those up if you want to work on them.

Yup sure. I hope to work on 404 page.