Designed PR template for repository. Issue #52
WalkingPal/walking-pal-web pull request #77
Opened 2022-10-03 17:19 UTC by tanmay-S12

Designed PR template for the repository as per the requirements. **Issue**  #52 . Hope you like it, if need some changes, pls let me know. (Updated)

2022-10-03 18:38 UTC, ashuvssut commented on .docs/PR_template.md
> +   <!--Put 'x' in the boxes that apply.!-->
These 2 lines are not needed

2022-10-03 18:39 UTC, ashuvssut requested changes

2022-10-03 18:39 UTC, ashuvssut commented on .docs/PR_template.md
> + * ### Link this PR to your issues by writing: fixes #issue_id OR closes #issue_id
this line is not needed

2022-10-03 18:39 UTC, ashuvssut commented on .docs/PR_template.md
> +* ### If you need help with you PR or if you want to to discuss something with us, join the **WalkingPal** [Discord community](https://discord.gg/Et3aQTsW6a)!
This line is not needed

2022-10-03 18:48 UTC, ashuvssut commented
`.docs` is not where PR templates are kept. you make use of `.github` folder and put `.yml` / `.md` files and stuff.

![image](https://user-images.githubusercontent.com/60546840/193654942-de09d985-255e-4e6c-865c-f8fadeace5fc.png)
refer https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

2022-10-04 06:00 UTC, tanmay-S12 commented
@ashuvssut I have committed the changes. Please check it now.

2022-10-04 08:23 UTC, ashuvssut commented
See the screenshot from the docs I showed you. follow that

2022-10-04 14:58 UTC, tanmay-S12 commented
Ohkay, I will make in into . GitHub/ pr template folder

On Tue, 4 Oct, 2022, 1:53 pm Ashutosh Khanduala, ***@***.***>
wrote:

> See the screenshot from the docs I showed you. follow that
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WalkingPal/walking-pal-web/pull/77#issuecomment-1266577221>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVZH2QVFIJTS7DW6UMXL7PDWBPSRBANCNFSM6AAAAAAQ3ZMYY4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-07 04:06 UTC, tanmay-S12 commented
@ashuvssut Please refer to PR #93. I have made the requested changes to it.

2022-10-07 13:38 UTC, ashuvssut commented
closing this PR. changes merged via #93 .

2022-10-07 13:38 UTC, closed without merging